---
- name: "Ouvrir les ports tcp (ssh, http, https, etc.)"
  ufw:
    rule: allow
    proto: tcp
    port: '{{ item }}'
  loop:
    - '22'
    - '80'
    - '443'
  become: yes
  
- name: "Ouvrir le port udp 1935 pour rtmp"
  ufw:
    rule: allow
    proto: udp
    port: '1935'
  become: yes

- name: "Activer ufw au besoin"
  ufw:
    name: ufw
    state: enabled
  become: yes
